version: 2
machine:
  node:
    version: 8.9.4
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    machine: true
    steps:
      - checkout
      - run: npm run coverage:report
